# File: EugeneZrazhevsky.WeblocOpener.installer.yaml
PackageIdentifier: EugeneZrazhevsky.WeblocOpener
PackageVersion: 2.0.2
InstallerType: inno
InstallerSwitches:
  Silent: "/VERYSILENT /NORESTART"
  SilentWithProgress: "/SILENT /NORESTART"
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/benchdoos/WeblocOpener/releases/download/v2.0.2.0/WeblocOpenerSetup.exe
    InstallerSha256: FEF503B9F03584CCC4CDBD92BAE67943B2A00CA07C4229AEFB019637F7A5A007
ManifestType: installer
ManifestVersion: 1.6.0
